name: promptwise
description: "Master AI Prompts & Detect Misinformation – Flutter educational app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.0
  supabase_flutter: 2.16.0
  http: ^1.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/branding/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/promptwise_app_icon_1024.png"
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/branding/promptwise_app_icon_1024.png"
    background_color: "#FFFFFF"
    theme_color: "#5B4CF0"
