name: promptwise
description: "Master AI Prompts & Detect Misinformation – Flutter educational app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.0
  supabase_flutter: 2.16.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/