import '../models/game_item.dart';

final List<GameRound> gameRounds = [
  GameRound(
    imagePathA: 'assets/images/real_sample.jpg',
    imagePathB: 'assets/images/ai_sample.jpg',
    isAAI: false,
    explanation: 'Image B was generated by AI. Look for unnatural details in hands, lighting, and background inconsistencies.',
  ),
];
