const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const get = p => fs.readFileSync(path.join(root, p), 'utf8');
let checks=0;
const check=(name,condition)=>{assert.ok(condition,name);console.log('PASS:',name);checks++;};
const sql=get('supabase/migrations/20260922040000_learner_onboarding_orientation.sql');
const routes=get('lib/core/routes/app_routes.dart');
const gate=get('lib/presentation/screens/auth/auth_gate_screen.dart');
const ctrl=get('lib/presentation/controllers/onboarding_controller.dart');
const screen=get('lib/presentation/screens/user/onboarding_orientation_screen.dart');
const pubspec=get('pubspec.yaml');
check('SQL migration backfills existing accounts',/insert into public\.learner_onboarding[\s\S]*?select id, now\(\) from auth\.users/.test(sql));
check('RLS on onboarding',/alter table public\.learner_onboarding enable row level security/.test(sql));
check('RLS restricts per user', (sql.match(/\(select auth\.uid\(\)\) = user_id/g)||[]).length>=3);
check('completion RPC uses invoker and server identity',/security invoker/.test(sql)&&/auth\.uid\(\)/.test(sql));
check('replay cannot clear watched history', /else learner_onboarding\.video_watched_at/.test(sql));
check('video asset exists and is registered',fs.existsSync(path.join(root,'assets/videos/promptwise_awareness.mp4')) && pubspec.includes('assets/videos/promptwise_awareness.mp4'));
check('player dependency registered',/video_player: \^2\.11\.1/.test(pubspec));
check('initial + direct routes both guard learners', (gate.match(/_LearnerOrientationGate\(/g)||[]).length>=3);
check('explicit replay route',routes.includes("case orientation:")&&routes.includes('requireOrientation: false'));
check('controller prevents stale account responses',ctrl.includes('generation != _generation'));
check('transcript and watch-later supported', screen.includes('Video transcript')&&screen.includes('Continue (watch later)'));
check('no forced completion on video error',screen.includes('Video unavailable.')&&screen.includes('watched: _watchedToEnd'));
console.log(`PASS: ${checks} source-contract checks (not a Flutter or live database test).`);
