const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const fn = fs.readFileSync(path.join(root, 'supabase/functions/content-automation/index.ts'), 'utf8');
const sql = fs.readFileSync(path.join(root, 'supabase/migrations/20260922020000_atomic_content_automation_run.sql'), 'utf8');
const smoke = fs.readFileSync(path.join(root, 'supabase/tests/atomic_content_automation_smoke.sql'), 'utf8');
const claimMatch = fn.match(/service\.rpc\(\s*'claim_content_automation_run',[\s\S]*?\);/);
assert.ok(claimMatch, 'Edge Function must use the atomic claim RPC');
assert.ok(fn.includes('if (claimError) throw claimError;'), 'RPC failures must fail closed');
assert.ok(fn.includes('if (claimedRunId === null)'), 'Busy claims must return without processing');
assert.ok(!fn.includes(".gte('started_at', staleCutoff)"), 'Remove racy SELECT-then-INSERT path');
assert.ok(!fn.includes(".insert({ trigger_mode: mode, status: 'running' })"), 'No direct start inserts');
assert.match(sql, /pg_catalog\.pg_advisory_xact_lock\(7262009, 1\)/);
assert.match(sql, /create unique index if not exists automation_runs_one_running_idx/);
assert.match(sql, /where status = 'running';/);
assert.match(sql, /security invoker/);
assert.match(sql, /grant execute on function public\.claim_content_automation_run\(text\) to service_role/);
assert.match(smoke, /rollback;/);
console.log('PASS: 11 source-contract checks (NOT a live database concurrency test).');
