-- PromptWise Phase 6 - Adaptive Learning
-- Run this once in Supabase Dashboard > SQL Editor.
-- It adds adaptive topic metadata and learner-owned adaptive progress tables.

begin;

-- 1) Content tagging for personalized recommendations.
alter table if exists public.content_items
  add column if not exists adaptive_topic text;

alter table if exists public.content_items
  drop constraint if exists content_items_adaptive_topic_check;

alter table if exists public.content_items
  add constraint content_items_adaptive_topic_check
  check (
    adaptive_topic is null or adaptive_topic in (
      'prompt_clarity',
      'context',
      'specificity',
      'responsible_use',
      'verification'
    )
  );

-- 2) One current mastery row per learner/topic.
create table if not exists public.topic_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id text not null check (topic_id in (
    'prompt_clarity',
    'context',
    'specificity',
    'responsible_use',
    'verification'
  )),
  mastery integer not null default 0 check (mastery between 0 and 100),
  attempts integer not null default 0 check (attempts >= 0),
  correct_answers integer not null default 0 check (correct_answers >= 0),
  last_practiced_at timestamptz,
  next_review_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, topic_id)
);

-- 3) Diagnostic assessment history.
create table if not exists public.assessment_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  assessment_type text not null default 'diagnostic',
  score integer not null check (score between 0 and 100),
  correct_answers integer not null default 0,
  total_questions integer not null default 0,
  answers jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null default now()
);

-- 4) Question/activity attempt history. Retries can be logged without
--    repeatedly increasing mastery through counted_for_mastery.
create table if not exists public.question_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  topic_id text not null check (topic_id in (
    'prompt_clarity',
    'context',
    'specificity',
    'responsible_use',
    'verification'
  )),
  is_correct boolean not null,
  attempt_type text not null default 'quiz',
  counted_for_mastery boolean not null default true,
  attempted_at timestamptz not null default now()
);

-- 5) Current spaced-review schedule per learner/topic.
create table if not exists public.review_schedule (
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id text not null check (topic_id in (
    'prompt_clarity',
    'context',
    'specificity',
    'responsible_use',
    'verification'
  )),
  due_at timestamptz not null,
  mastery_snapshot integer not null default 0 check (mastery_snapshot between 0 and 100),
  updated_at timestamptz not null default now(),
  primary key (user_id, topic_id)
);

create index if not exists idx_assessment_attempts_user_completed
  on public.assessment_attempts (user_id, completed_at desc);
create index if not exists idx_question_attempts_user_attempted
  on public.question_attempts (user_id, attempted_at desc);
create index if not exists idx_question_attempts_user_topic
  on public.question_attempts (user_id, topic_id);
create index if not exists idx_review_schedule_user_due
  on public.review_schedule (user_id, due_at);

-- RLS: learners can only read/write their own adaptive records.
-- Administrators may read adaptive progress for future reporting, but learner
-- writes are still restricted to the authenticated learner's own user_id.
alter table public.topic_mastery enable row level security;
alter table public.assessment_attempts enable row level security;
alter table public.question_attempts enable row level security;
alter table public.review_schedule enable row level security;

drop policy if exists "topic_mastery_select_own_or_admin" on public.topic_mastery;
create policy "topic_mastery_select_own_or_admin"
on public.topic_mastery for select
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'administrator'
  )
);

drop policy if exists "topic_mastery_insert_own" on public.topic_mastery;
create policy "topic_mastery_insert_own"
on public.topic_mastery for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "topic_mastery_update_own" on public.topic_mastery;
create policy "topic_mastery_update_own"
on public.topic_mastery for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "assessment_attempts_select_own_or_admin" on public.assessment_attempts;
create policy "assessment_attempts_select_own_or_admin"
on public.assessment_attempts for select
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'administrator'
  )
);

drop policy if exists "assessment_attempts_insert_own" on public.assessment_attempts;
create policy "assessment_attempts_insert_own"
on public.assessment_attempts for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "question_attempts_select_own_or_admin" on public.question_attempts;
create policy "question_attempts_select_own_or_admin"
on public.question_attempts for select
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'administrator'
  )
);

drop policy if exists "question_attempts_insert_own" on public.question_attempts;
create policy "question_attempts_insert_own"
on public.question_attempts for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "review_schedule_select_own_or_admin" on public.review_schedule;
create policy "review_schedule_select_own_or_admin"
on public.review_schedule for select
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'administrator'
  )
);

drop policy if exists "review_schedule_insert_own" on public.review_schedule;
create policy "review_schedule_insert_own"
on public.review_schedule for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "review_schedule_update_own" on public.review_schedule;
create policy "review_schedule_update_own"
on public.review_schedule for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

commit;

-- OPTIONAL AFTER RUNNING THE MIGRATION:
-- In PromptWise Admin > Content Management, edit important modules, lessons,
-- quizzes, and verification activities and choose an Adaptive learning topic.
-- If left as Automatic, the app uses keyword-based topic inference.
